# gDR style

## General

1. Indentation
  * 2 spaces for indentation
2. Use of spaces
  * Always utilize `if (` over `if(`
  * Always include spaces around logical comparison `1 == 1` over `1==1`
  * Always include spaces around logical entity `if (1 == 1) {}` over `if (1=1){}`
3. Naming conventions
  * variables
    * Utilize lower_snake_case for variables
  * function arguments
    * Utilize space between function arguments `function(a = "A")` over `function(a="A")`
    * Utilize lower_snake_case for function arguments `function(big_matrix)` over `function(bigMatrix)`
  * function names
    * All action functions should start with verbs `compute_metrics_SE` over `metrics_SE`
    * All internal functions start with a `.`
    * Utilize lowerCamelCase for function names
4. Functions, functions, functions
  * Function assignment
    * Always utilize `<-` over `=` to differentiate function arguments from function assignments `myFunction <- function()` over `myFunction = function()`
  * Function export
    * All internal functions are not exported
  * `vapply` over `sapply` (or `lapply` + `unlist()` if predefining FUN.VALUE is difficult)
  * Do not use `apply` on data.frame(s) (`mapply` is good for row-wise operations) 
6. Use of curly braces
  * `if` and `else` statements should be surrounded by curly braces on the same line

```{r}
if () {
  NULL
} else {
  NULL
}
```

7. Miscellaneous
  * Exponentiation: always utilize `^` over `**` for exponentiation like `2 ^ 3` over `2**3`.
