# This workflow is used to update static webpage with documentation for the given GitHub repository.
# It's triggered by the push of the default branch.
# More details: https://docs.google.com/document/d/1WGW4_lOOZ73lEfVZwIWMivbyCgDTJAajxP5N8767DZY

name: pkgdown

on:
  push:
    branches: [main, master, test_ci_pkgdown]
  release:
    types: [published]
  workflow_call:
    inputs:
      USERNAME:
        required: true
        type: string
      PACKAGE_NAME:
        required: true
        type: string
      BRANCH_NAME:
        required: true
        type: string
      IS_SUBDIR:
        description: "Is the R package stored as the subdirectory of the repository?"
        required: false
        type: string
        default: 'false'

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
          needs: website

      - name: Build pkgdown site
        if: ${{ inputs.IS_SUBDIR != 'true' }}
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = TRUE)
        shell: Rscript {0}

      - name: Build pkgdown site (subdirectory)
        if: ${{ inputs.IS_SUBDIR == 'true' }}
        run: pkgdown::build_site_github_pages(pkg = "${{ inputs.PACKAGE_NAME }}", new_process = FALSE, install = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        if: ${{ inputs.IS_SUBDIR != 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: true
          branch: pages
          folder: docs
          target-folder: docs

      - name: Deploy to GitHub pages (subdirectory)
        if: ${{ inputs.IS_SUBDIR == 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: true
          branch: pages
          folder: ${{ inputs.PACKAGE_NAME }}/docs
          target-folder: docs
